### ISSUE TITLE
error TS6053: File 'node_modules/tns-platform-declarations/tns-core-modules/ios.d.ts' not found.

### ISSUE THREAD

**Issue by tkaarrela** [NathanWalker/nativescript-plugin-seed#12]
I faced following issue when running 'npm run setup'

error TS6053: File 'node_modules/tns-platform-declarations/tns-core-modules/ios.d.ts' not found.

**Comment by jamesehly** [comment]
I also have this issue.  Is this because I'm developing on Windows?

**Comment by tkaarrela** [comment]
I'm developing on osx

**Comment by WinMinTun** [comment]
Yeah Me too. But add that file and build for temporary workaround.

**Comment by EddyVerbruggen** [comment]
That file had to move in 2.3.0. [Here's a similar bug report on the NativeScript repo.](https://github.com/NativeScript/NativeScript/issues/2724)

**Comment by NathanWalker** [comment]
Latest master now has solid fix for this 👍
