### ISSUE TITLE
add extra option for custom name prefix on postclone script

### ISSUE THREAD

**Issue by ryc16** [NathanWalker/nativescript-plugin-seed#13]
@NathanWalker, nice plugin-seed. Currently, the postclone.js helps to change classname but it always has "nativescript" as name prefix for package. Is it possible to put extra option to have custom name prefix not always "nativescript".

For example, if I want to create a contacts class, if I put "contacts" as class name, postclone will create nativescript-contacts which seem often to overlap with other people's plugin. If I use "myapp-contacts", then the classname is "MyappContacts" sounds strange. So, if there is option to name-prefix, I could have name prefix ie "ns-myname" and classname "contacts", the postclone will create plugin as "ns-myname -contacts" and keep classname "Contacts" to avoid conflict with others package.

Thanks

**Comment by EddyVerbruggen** [comment]
@ryc16 I think it's nice to have a common prefix for all our {N} plugins and the defacto standard seems to be `nativescript-`.

Perhaps in your example the new contacts plugin has a very specific feature only, like retrieving (a bit silly, sorry) only firstnames. Then the plugin could become `nativescript-firstname-contacts` or something like that.

Or better still, it could become a fork of the contacts plugin and send the new feature upstream as a PR so we keep the plugin landscape nice and tidy.

Just my opinion, nothing more.

**Comment by ryc16** [comment]
@EddyVerbruggen, understood. i think it makes sense to keep the standard if it is for public. So that is why make it as optional argument. In some case, I just want to use for personal but not share out. In this case, I probably like to more control and shorten a bit for the name. For example, ns-companyname-classname, where ns still refer to {N} plugins. Once again, just nice to have.

**Comment by NathanWalker** [comment]
@ryc16 If you'd like to submit a PR with that option, we could entertain that.
However, since the seed is primarily for public consumption, using the `nativescript-` prefix is helpful to ensure a developer doesn't end up publishing a plugin without a standard naming scheme by mistake.

**Comment by NathanWalker** [comment]
I'm going to close this as using the `nativescript-` prefix is definitely advisable and preferred.
