### ISSUE TITLE
style.Styler is not exported

### ISSUE THREAD

**Issue by VladimirMilenko** [NathanWalker/nativescript-plugin-seed#17]
Hello. Got an issue, in examples, such as cardview and others, they are using Styler class, which is declared in style.d.ts, which is located at ui/styling.
But after cloning this repo i can't extend this Styler class.
Is this issue connected with nativescript-plugin-seed or it's about changes in NativeScript API?

**Comment by NathanWalker** [comment]
@VladimirMilenko it's not related to the seed but rather tns core modules. You can still use the ui/styling module like cardview and others are doing - it will work fine even if the TSC compiler gives warning.
