### ISSUE TITLE
Errors trying to run

### ISSUE THREAD

**Issue by patrickpereira** [NathanWalker/nativescript-plugin-seed#19]
Hi Nathan,

By following the instructions to the point and the running npm run demo.ios, I get the following errors

error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.

And finally this one:

1   0x104b338d7 -[TNSRuntime executeModule:]
2   0x1046d9572 main
3   0x108a5268d start
file:///app/app.js:2:26: JS ERROR Error: Could not find module 'application'. Computed path '/Users/patrickpereira/Library/Developer/CoreSimulator/Devices/6B5900B6-5778-4852-9243-1D3BE3B67E6E/data/Containers/Bundle/Application/B76297F2-2002-432E-98AD-4B851B8A0713/demo.app/app/tns_modules/application'.
Feb  8 15:04:55 Patricks-MacBook-Pro-2 com.apple.CoreSimulator.SimDevice.6B5900B6-5778-4852-9243-1D3BE3B67E6E.launchd_sim[9950] (UIKitApplication:org.nativescript.demo[0x549b][27801]): Service exited due to Segmentation fault: 11

What is the issue?

**Comment by NathanWalker** [comment]
Hi @patrickpereira thank you for reporting this. The demo references file was missing.
Please try following the instructions [here](https://github.com/NathanWalker/nativescript-plugin-seed#getting-started) once more and it should work for you.
