### ISSUE TITLE
Rename plugin, how?

### ISSUE THREAD

**Issue by alexrainman** [NathanWalker/nativescript-plugin-seed#20]
I renamed my plugin from "nativescript-nsappconnect" to "nativescript-mobileiron-appconnect" and now when i run:

```
npm run demo.ios
```

The script is looking to remove the old one and i cannot run the demo:

```
> npm run build && cd demo && tns plugin remove nativescript-nsappconnect && tns plugin add .. && tns install


> nativescript-mobileiron-appconnect@1.0.0 build /Users/alexrainman/Github/nativescript-mobileiron-appconnect
> tsc

Plugin "nativescript-nsappconnect" is not installed.
```

Help?

**Comment by NathanWalker** [comment]
@alexrainman You will have to update your `package.json` scripts and other various things to rename.
See this in your plugin: https://github.com/NathanWalker/nativescript-plugin-seed/blob/master/package.json#L21

You'll want to reflect your rename there.

**Comment by alexrainman** [comment]
That line fixed my problem. Thanks
