### ISSUE TITLE
npm run demo.ios is addin tns-android as dependency

### ISSUE THREAD

**Issue by alexrainman** [NathanWalker/nativescript-plugin-seed#21]
No matter if i delete it i end up having this

```
"dependencies": {
    "nativescript-mobileiron-appconnect": "file:///Users/alexrainman/Github/nativescript-mobileiron-appconnect",
    "nativescript-unit-test-runner": "^0.3.0",
    "tns-android": "^2.5.0",
    "tns-core-modules": "^2.5.0"
  }
```

Then my iOS app is 33 MB bigger.

**Comment by NathanWalker** [comment]
Thanks again @alexrainman yes, that is actually an issue with 2.5 - just pushed up fix to seed to ensure it is not in deps section - however if it comes back and you get an error as a result, just ensure the demo has that removed from deps and then run again 👍

**Comment by alexrainman** [comment]
Whats the fix actually?

**Comment by NathanWalker** [comment]
Remove `tns-android` from `dependencies` section ;)

**Comment by alexrainman** [comment]
Where? In demo? I remove it but it comes back again as soon as i run ```npm run demo.ios```

**Comment by NathanWalker** [comment]
In demo - if you pulled latest, it should not come back. It may show up for a moment but then go back away during the build.

**Comment by alexrainman** [comment]
Whats is the fix you applied so i can do it in a plugin already developed?

**Comment by NathanWalker** [comment]
Ensure it is not in dependencies of the demo and that it's not committed to the repo like that and it should be good. Also update the demo.ios package script to use 'tns run ios --emulator' as the last command in the chain instead of 'tns emulate ios'

**Comment by alexrainman** [comment]
Worked. Thanks

**Comment by alexrainman** [comment]
We are getting close to release MobileIron plugin for NativeScript :)
