### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by patrickpereira** [NathanWalker/nativescript-plugin-seed#23]
Hi Nathan (or anybody else that are Nativescript plugin experts),

I'm not in any way confident in making plugins yet and everything looks really overwhelming, when you haven't touched Objective C before and the delegate thing really throws me off... But I'm willing to learn!

I'm trying to make a plugin for the payment solution Visa Checkout for iOS. I'm provided with .framework files and an SDK. 

I have a fresh install of your seed w. typescript installed and I've added the .framework files (which contains module.modulemap) to the platforms/ios folder, furthermore I've added a build.xcconfig file, with the following content (but it's more or less a guess with info from the SDK):

OTHER_LDFLAGS = -all_load, -ObjC, -lc++

According to the docs, there are come steps I need to do, in order to get it up and running, and I'm more or less clueless on exactly how and where to do it in connection with the plugin.

1. 

Import VisaCheckoutFramework.h into your view controller and adopt the
VisaLibraryDelegate protocol.
#import <UIKit/UIKit.h>
#import <VisaCheckoutFramework/VisaCheckoutFramework.h>
@interface ViewController : UIViewController <VisaLibraryDelegate>
@end
Important:
You must implement all required methods in VisaLibraryDelegate.h.

2.

Add the Visa Checkout button to your view.
There are 2 variations of the button, a standard button and a neutral button. You
should use the standard button unless the background colors in your app are dark,
in which case, you can consider using a neutral button to provide greater contrast.
You can add the Visa Checkout button in one of two ways, either through code or
through the storyboard view.
Note: –The frame width determines the actual size of a Visa Checkout button,
whose height is sized to retain the original aspect ratio. The frame width
must be between 154 points and 213 points, inclusive. The origin (x and y
coordinates) you specify position the button at the desired location.
For an express checkout button, the width must be between 213 pixels, up to
the screen width. The height is 77 pixels.
• Code method:
If you are using a Visa Checkout button, add the following button code to your
loadView or viewDidLoad method:
VisaCheckoutButton *checkoutButton =
[[VisaCheckoutButton alloc] initWithFrame: CGRectMake
(30, 80, 0, 0)];
checkoutButton.delegate = self;
// Set the button color to neutral, if necessary
// self.checkoutButton.color = VisaCheckoutButtonColorNeutral;
[self.view addSubview:checkoutButton];
If you are using an express checkout button, add the following button code to
your loadView or viewDidLoad method:
//Add the following button code to your loadView or viewDidLoad
VisaExpressCheckoutView *exoButtonContainer =
[[VisaExpressCheckoutView alloc] initWithFrame: CGRectMake
(0, 0, 200, 77)];
exoButtonContainer.expressCheckoutdelegate = self;
// Set the button color to neutral, if necessary
exoButtonContainer.color = VisaCheckoutButtonColorNeutral;
[self.view addSubview:exoButtonContainer];

3.

Implement the VisaLibraryDelegate methods for the Visa Checkout Sandbox
or production servers. For more information, see Visa Checkout Library Delegate
Methods. 

I've attached the SDK for more info. Hope you can help me out here, as I've been struggling for quite a while... :-)

[VisaCheckoutSDKiOSV43.pdf](https://github.com/NathanWalker/nativescript-plugin-seed/files/769093/VisaCheckoutSDKiOSV43.pdf)

Best regards
Patrick

**Comment by patrickpereira** [comment]
The framework files can be downloaded here - if needed: http://www.rightbeforebeta.com/VisaCheckout-iOS-SDK-4.3.4.zip

**Comment by NathanWalker** [comment]
@patrickpereira happy we were able to get ya going 👍

**Comment by patrickpereira** [comment]
Yes thanks soo much @NathanWalker !!! Now I'm going to be looking at the Android version of the plugin.
