### ISSUE TITLE
Cannot find module <your-plugin-name> from demo project

### ISSUE THREAD

**Issue by alexziskind1** [NathanWalker/nativescript-plugin-seed#3]
This is a great template! There is one issue I'm running into. After completing all the steps, I see that the plugin module is not found in my demo tns project. So I don't get intellisense when using the plugin in the app. How do you recommend exposing the plugin API to the app itself...
1. during the demo app development?
2. during plugin consumer app development?

Thanks!

**Comment by NathanWalker** [comment]
Thanks @alexziskind1 just seeing this!
There's a couple modifications I need to make namely a `typings` key needs to be added to package and `'declarations': true` needs to be set in tsconfig... i'll update seed over weekend to fix and close this when it's ready to check out. thx for the ping!

**Comment by NathanWalker** [comment]
@alexziskind1 just pushed up fixes to master that solve both concerns you mention.
package is now setup correctly for typings to be published with the plugin and the demo picks it up correctly as well 👍

**Comment by alexziskind1** [comment]
Very nice! I'm checking it out now, seems like a few other files are missing now when I follow the README and do `npm run setup`. Should I open another issue or you're going to check it out?

**Comment by NathanWalker** [comment]
@alexziskind1 hey sry,  just saw this! Which files show missing for ya?
