### ISSUE TITLE
Issue with 2.2 and .d.ts files

### ISSUE THREAD

**Issue by tjvantoll** [NathanWalker/nativescript-plugin-seed#4]
Just as an fyi that, as is, this plugin generator is going to break when you upgrade to 2.2 because of changes to tns-platform-declarations. I’ll give details (and hopefully a PR) when we figure out what’s up, but for now I just wanted to let you know so you don’t waste time debugging this. Might want to follow https://github.com/NathanaelA/tns-template-plugin/issues/5.

**Comment by roblav96** [comment]
Agreed.

Just getting into TNS plugins and would like to use this seed =]

**Comment by tjvantoll** [comment]
Just as an fyi here’s how Nathanael worked around the problem https://github.com/NathanaelA/tns-template-plugin/commit/ebeb8ad993d83cc5ec7eedc63441cb0acfd14715. I’ll see if I have time to put a PR together later today. Community contributions are also welcome 😄

**Comment by tjvantoll** [comment]
Oh hey, I actually did something! Here’s the PR to upgrade this seed to work with 2.2: https://github.com/NathanWalker/nativescript-plugin-seed/pull/6.
