### ISSUE TITLE
Notes on adding platform specific dependencies

### ISSUE THREAD

**Issue by getmetorajesh** [NathanWalker/nativescript-plugin-seed#9]
would be handy to see references for platform specific dependencies added to the docs,

```
platforms
   ios
      Podfile
   android
      include.gradle 
      [or] .jar file
```

**Comment by EddyVerbruggen** [comment]
I like the idea. Perhaps it's best to just link to a few plugins where those concepts are used.

**Comment by NathanWalker** [comment]
Thanks for the suggestion @getmetorajesh , I have put a note in README about this:
https://github.com/NathanWalker/nativescript-plugin-seed#linking-to-cocoapod-or-android-arsenal-plugins
